### PR TITLE
Fix build for KDE 6.1

### PR DESCRIPTION
**Pull request by sr-tream**

### CODE REVIEW

**Comment by scgm0** [comment]
Is there any difference between this PR and https://github.com/a-parhom/LightlyShaders/pull/144?

**Comment by sr-tream** [comment]
> Is there any difference between this PR and #144?

I didn't look at this PR, when creates own.

#144 looks more safe in work with OGL context, but do not fix linking with xcb

**Comment by AldanTanneo** [comment]
> > Is there any difference between this PR and #144?
> 
> I didn't look at this PR, when creates own.
> 
> #144 looks more safe in work with OGL context, but didn't fix linking with xcb

I can add a commit to mine to fix the linking if you want

**Comment by sr-tream** [comment]
> > > Is there any difference between this PR and #144?
> > 
> > 
> > I didn't look at this PR, when creates own.
> > #144 looks more safe in work with OGL context, but didn't fix linking with xcb
> 
> I can add a commit to mine to fix the linking if you want, it's just that I didn't run into the issue when I built it

Add it please

**Comment by AldanTanneo** [comment]
@sr-tream I don't understand why the xcb randr component is needed however

**Comment by sr-tream** [comment]
> @sr-tream I don't understand why the xcb randr component is needed however

It's provided some symbol, what required on my laptop to build with kwin 6.1.0. Currently, I tested it on PC with kwin 6.1.1, and it works without xcb and xcb-randr

**Pull request closed without merging**
